[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"
ffi = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@compound-protocol/=lib/compound-protocol",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",

]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config